/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare-multi-worker/incidents-service-api-worker/wrangler.jsonc --include-runtime=false --env-interface=IncidentsServiceEnv cloudflare-multi-worker/incidents-service-api-worker/worker-configuration.d.ts` (hash: 80b1eac1832548230deddca62d6f41da)
interface __BaseEnv_IncidentsServiceEnv {
	INCIDENTS_DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_IncidentsServiceEnv {}
}
interface IncidentsServiceEnv extends __BaseEnv_IncidentsServiceEnv {}
