/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare-multi-worker/api-gateway-worker/wrangler.jsonc --include-runtime=false --env-interface=GatewayEnv cloudflare-multi-worker/api-gateway-worker/worker-configuration.d.ts` (hash: 0c68cfde7889717fdb486bda8c2140a2)
interface __BaseEnv_GatewayEnv {
	ALLOW_ANONYMOUS: "false";
	REALTIME_SHARDS: "4";
	REALTIME: DurableObjectNamespace<import("./src/index").RealtimeGatewayDO>;
	TASKS_SERVICE: Fetcher /* livequery-tasks-service-api */;
	INCIDENTS_SERVICE: Fetcher /* livequery-incidents-service-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RealtimeGatewayDO";
	}
	interface Env extends __BaseEnv_GatewayEnv {}
}
interface GatewayEnv extends __BaseEnv_GatewayEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOW_ANONYMOUS" | "REALTIME_SHARDS">> {}
}
