/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare-multi-worker/tasks-service-api-worker/wrangler.jsonc --include-runtime=false --env-interface=TasksServiceEnv cloudflare-multi-worker/tasks-service-api-worker/worker-configuration.d.ts` (hash: 35031922140cd8ed14c2d3388cd1fb5e)
interface __BaseEnv_TasksServiceEnv {
	TASKS_DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_TasksServiceEnv {}
}
interface TasksServiceEnv extends __BaseEnv_TasksServiceEnv {}
