import { createServiceTopology } from '@livequery/gateway-controller'
import type { ServiceManifest } from '@livequery/service'

function safeName(value: string): string {
  return `livequery_${value.replace(/[^a-zA-Z0-9_]/g, '_')}`
}

function routeExpression(path: string): string {
  const segments = path.split('/').filter(Boolean).map(segment => {
    if (segment.startsWith(':')) return '[^/]+'
    const colon = segment.indexOf(':')
    return colon < 0 ? segment.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') : `${segment.slice(0, colon)}[^/]+`
  })
  return `^/${segments.join('/')}/?$`
}

export function renderNginxConfig(manifests: readonly ServiceManifest[]): string {
  const services = createServiceTopology(manifests)
  const blocks: string[] = ['# Generated by @livequery/gateway-controller-nginx']
  for (const service of services) {
    const upstream = safeName(service.serviceId)
    blocks.push(`upstream ${upstream} {`)
    for (const target of service.targets) blocks.push(`  server ${target.host}:${target.port};`)
    blocks.push('}', '')
    const routeGroups = new Map<string, typeof service.routes>()
    for (const route of service.routes) {
      if (route.targetPath) throw new Error(`Nginx renderer does not support targetPath yet: ${route.id}`)
      const routes = routeGroups.get(route.path) ?? []
      routes.push(route)
      routeGroups.set(route.path, routes)
    }
    for (const [path, routes] of routeGroups) {
      const methods = [...new Set(routes.map(route => route.method.toUpperCase()))].join(' ')
      blocks.push(`location ~ ${routeExpression(path)} {`)
      blocks.push(`  limit_except ${methods} { deny all; }`)
      blocks.push(`  proxy_pass ${service.protocol}://${upstream};`)
      blocks.push('  proxy_set_header Host $host;')
      blocks.push('  proxy_set_header X-Request-Id $request_id;')
      blocks.push('}', '')
    }
  }
  return `${blocks.join('\n')}\n`
}
