/**
 * Probe: what MongoDB accepts as a client-chosen `_id`, against a real server.
 *
 *   LIVEQUERY_E2E_MONGO_URL='mongodb://user:pass@host:27018/?directConnection=true' \
 *     bun tests/scripts/mongo-custom-id.probe.ts
 *
 * Runs in a throwaway collection that is dropped at the end. Prints one line per check.
 */

import { Binary, MongoClient, ObjectId, UUID } from 'mongodb'
import { uuidv7 } from 'uuidv7'
import { AUTH_SOURCE, DB_NAME, MONGO_URL } from '../helpers/env.js'

const results: Array<{ check: string, ok: boolean, detail: string }> = []
const record = (check: string, ok: boolean, detail: string) => {
    results.push({ check, ok, detail })
    console.log(`${ok ? 'PASS' : 'FAIL'}  ${check}\n      ${detail}`)
}

const errorText = (e: any) => `${e?.code ?? ''} ${e?.codeName ?? ''} ${String(e?.message ?? e).split('\n')[0]}`.trim()

const client = new MongoClient(MONGO_URL, { authSource: AUTH_SOURCE, serverSelectionTimeoutMS: 15000 })
await client.connect()
const info = await client.db('admin').command({ buildInfo: 1 })
console.log(`MongoDB ${info.version} — db "${DB_NAME}"\n`)

const name = `probe_custom_id_${Date.now()}`
const col = client.db(DB_NAME).collection<any>(name)

try {
    // 1. uuidv7 string as _id
    const v7 = uuidv7()
    await col.insertOne({ _id: v7, title: 'uuidv7 string' })
    const found_v7 = await col.findOne({ _id: v7 })
    record('insert _id = uuidv7 string, read it back', found_v7?.title === 'uuidv7 string', `_id: ${v7}, type: ${typeof found_v7?._id}`)

    // 2. inserting the same _id again → E11000
    try {
        await col.insertOne({ _id: v7, title: 'duplicate' })
        record('second insert with the same _id is rejected', false, 'insert succeeded — no uniqueness!')
    } catch (e: any) {
        record('second insert with the same _id is rejected', e?.code === 11000, errorText(e))
    }
    const copies = await col.countDocuments({ _id: v7 })
    record('still exactly one document after the duplicate attempt', copies === 1, `count: ${copies}`)

    // 3. ObjectId generated client-side (what drivers always do)
    const oid = new ObjectId()
    await col.insertOne({ _id: oid, title: 'client ObjectId' })
    const found_oid = await col.findOne({ _id: oid })
    record('insert _id = ObjectId generated by the client', found_oid?._id instanceof ObjectId, `_id: ${oid.toHexString()}, getTimestamp(): ${oid.getTimestamp().toISOString()}`)

    // 4. fully random 12 bytes as an ObjectId — Mongo does not check the "timestamp" part
    const random_bytes = crypto.getRandomValues(new Uint8Array(12))
    const random_oid = new ObjectId(random_bytes)
    await col.insertOne({ _id: random_oid, title: 'random 12 bytes' })
    const found_random = await col.findOne({ _id: random_oid })
    record('insert _id = 12 random bytes as ObjectId (timestamp part is garbage)', !!found_random, `_id: ${random_oid.toHexString()}, getTimestamp(): ${random_oid.getTimestamp().toISOString()}`)

    // 5. uuidv7 as BSON UUID (Binary subtype 4)
    const v7_bin = new UUID(uuidv7())
    await col.insertOne({ _id: v7_bin, title: 'uuidv7 binary' })
    const found_bin = await col.findOne({ _id: v7_bin })
    record('insert _id = uuidv7 as BSON UUID (Binary subtype 4)', found_bin?._id instanceof Binary && found_bin._id.sub_type === 4, `_id: ${v7_bin.toHexString()}`)

    // 6. type must match when querying: a string never equals an ObjectId with the same hex
    const as_string = await col.findOne({ _id: oid.toHexString() })
    record('querying an ObjectId _id with its hex STRING finds nothing (types must match)', as_string === null, `findOne({ _id: "${oid.toHexString()}" }) → ${as_string === null ? 'null' : 'found'}`)
    const v7_as_oid = ObjectId.isValid(v7)
    record('a uuidv7 string is not a valid ObjectId (so the two kinds never collide)', !v7_as_oid, `ObjectId.isValid("${v7}") → ${v7_as_oid}`)

    // 7. mixed types sort by BSON type order, not by time
    const order = (await col.find({}, { projection: { title: 1 } }).sort({ _id: 1 }).toArray()).map(d => d.title)
    record('sort on _id with mixed types groups by BSON type (string < binary < ObjectId)', order.length === 4, order.join('  →  '))

    // 8. forbidden: array as _id
    try {
        await col.insertOne({ _id: [1, 2], title: 'array' })
        record('array _id is rejected', false, 'insert succeeded')
    } catch (e: any) {
        record('array _id is rejected', true, errorText(e))
    }

    // 9. _id is immutable once written
    try {
        await col.updateOne({ _id: v7 }, { $set: { _id: uuidv7() } })
        record('_id cannot be changed after insert', false, 'update succeeded')
    } catch (e: any) {
        record('_id cannot be changed after insert', true, errorText(e))
    }

    // 10. the dedupe pattern the datasource will use: insert, on 11000 read back in scope
    const doc_id = uuidv7()
    const insertOrGet = async (body: Record<string, any>, keys: Record<string, any>) => {
        try {
            await col.insertOne({ _id: doc_id, ...keys, ...body })
            return { outcome: 'inserted', doc: await col.findOne({ _id: doc_id }) }
        } catch (e: any) {
            if (e?.code !== 11000) throw e
            const existing = await col.findOne({ _id: doc_id, ...keys })
            return existing ? { outcome: 'existing (retry)', doc: existing } : { outcome: '409 ID_CONFLICT', doc: null }
        }
    }
    const first = await insertOrGet({ title: 'retry me' }, { owner: 'alice' })
    const retry = await insertOrGet({ title: 'retry me' }, { owner: 'alice' })
    const other_tenant = await insertOrGet({ title: 'steal' }, { owner: 'mallory' })
    record(
        'dedupe pattern: first insert, retry returns the same doc, other tenant gets a conflict',
        first.outcome === 'inserted' && retry.outcome === 'existing (retry)' && other_tenant.outcome === '409 ID_CONFLICT'
            && (await col.countDocuments({ _id: doc_id })) === 1,
        `first: ${first.outcome}, retry: ${retry.outcome}, other tenant: ${other_tenant.outcome}`,
    )
} finally {
    await col.drop().catch(() => undefined)
    await client.close()
}

const failed = results.filter(r => !r.ok)
console.log(`\n${results.length - failed.length}/${results.length} checks passed; collection "${name}" dropped.`)
process.exit(failed.length > 0 ? 1 : 0)
